<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\CashBankBook;

class CashBankBookFakeDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $fakeBooks = [
            [
                'name' => 'HDFC BANK',
                'alter_code' => 'HDFC-001',
                'under' => 'CASH & BANK BALANCES',
                'opening_balance' => 15000000.00,
                'opening_balance_type' => 'D',
                'credit_card' => 'N',
                'bank_charges' => 500.00,
                'address' => 'SECTOR 18, NOIDA',
                'address1' => 'NOIDA - 201301',
                'input_gst_purchase' => false,
                'output_gst_income' => false,
                'account_no' => '0123456789012345',
                'report_no' => null,
                'cheque_clearance_method' => 'I',
                'flag' => null,
                'receipts' => 'S',
                'transaction_date' => now(),
                'transaction_type' => 'Bank',
                'particulars' => 'Opening Balance',
                'debit' => 0,
                'credit' => 0,
                'balance' => 0,
            ],
            [
                'name' => 'ICICI BANK',
                'alter_code' => 'ICICI-001',
                'under' => 'CASH & BANK BALANCES',
                'opening_balance' => 8500000.00,
                'opening_balance_type' => 'D',
                'credit_card' => 'Y',
                'bank_charges' => 750.00,
                'address' => 'CONNAUGHT PLACE',
                'address1' => 'NEW DELHI - 110001',
                'input_gst_purchase' => true,
                'output_gst_income' => false,
                'account_no' => '9876543210123456',
                'report_no' => null,
                'cheque_clearance_method' => 'P',
                'flag' => null,
                'receipts' => 'I',
                'transaction_date' => now(),
                'transaction_type' => 'Bank',
                'particulars' => 'Opening Balance',
                'debit' => 0,
                'credit' => 0,
                'balance' => 0,
            ],
            [
                'name' => 'AXIS BANK',
                'alter_code' => 'AXIS-001',
                'under' => 'CASH & BANK BALANCES',
                'opening_balance' => 12000000.00,
                'opening_balance_type' => 'D',
                'credit_card' => 'N',
                'bank_charges' => 600.00,
                'address' => 'BANDRA KURLA COMPLEX',
                'address1' => 'MUMBAI - 400051',
                'input_gst_purchase' => false,
                'output_gst_income' => true,
                'account_no' => '1111222233334444',
                'report_no' => null,
                'cheque_clearance_method' => 'I',
                'flag' => null,
                'receipts' => 'S',
                'transaction_date' => now(),
                'transaction_type' => 'Bank',
                'particulars' => 'Opening Balance',
                'debit' => 0,
                'credit' => 0,
                'balance' => 0,
            ],
            [
                'name' => 'KOTAK BANK',
                'alter_code' => 'KOTAK-001',
                'under' => 'CASH & BANK BALANCES',
                'opening_balance' => 5500000.00,
                'opening_balance_type' => 'D',
                'credit_card' => 'W',
                'bank_charges' => 400.00,
                'address' => 'FORT, MUMBAI',
                'address1' => 'MUMBAI - 400001',
                'input_gst_purchase' => true,
                'output_gst_income' => true,
                'account_no' => '5555666677778888',
                'report_no' => null,
                'cheque_clearance_method' => 'P',
                'flag' => null,
                'receipts' => 'I',
                'transaction_date' => now(),
                'transaction_type' => 'Bank',
                'particulars' => 'Opening Balance',
                'debit' => 0,
                'credit' => 0,
                'balance' => 0,
            ],
            [
                'name' => 'INDUSIND BANK',
                'alter_code' => 'INDUSIND-001',
                'under' => 'CASH & BANK BALANCES',
                'opening_balance' => 7200000.00,
                'opening_balance_type' => 'D',
                'credit_card' => 'N',
                'bank_charges' => 550.00,
                'address' => 'BANGALORE',
                'address1' => 'BANGALORE - 560001',
                'input_gst_purchase' => false,
                'output_gst_income' => false,
                'account_no' => '9999000011112222',
                'report_no' => null,
                'cheque_clearance_method' => 'I',
                'flag' => null,
                'receipts' => 'S',
                'transaction_date' => now(),
                'transaction_type' => 'Bank',
                'particulars' => 'Opening Balance',
                'debit' => 0,
                'credit' => 0,
                'balance' => 0,
            ],
            [
                'name' => 'PETTY CASH',
                'alter_code' => 'PETTY-001',
                'under' => 'CASH IN HAND',
                'opening_balance' => 50000.00,
                'opening_balance_type' => 'D',
                'credit_card' => null,
                'bank_charges' => null,
                'address' => 'HEAD OFFICE',
                'address1' => 'MAIN STORE',
                'input_gst_purchase' => false,
                'output_gst_income' => false,
                'account_no' => null,
                'report_no' => null,
                'cheque_clearance_method' => 'P',
                'flag' => null,
                'receipts' => 'S',
                'transaction_date' => now(),
                'transaction_type' => 'Cash',
                'particulars' => 'Opening Balance',
                'debit' => 0,
                'credit' => 0,
                'balance' => 0,
            ],
            [
                'name' => 'OFFICE CASH',
                'alter_code' => 'OFFICE-001',
                'under' => 'CASH IN HAND',
                'opening_balance' => 100000.00,
                'opening_balance_type' => 'D',
                'credit_card' => null,
                'bank_charges' => null,
                'address' => 'OFFICE PREMISES',
                'address1' => 'CASH COUNTER',
                'input_gst_purchase' => false,
                'output_gst_income' => false,
                'account_no' => null,
                'report_no' => null,
                'cheque_clearance_method' => 'P',
                'flag' => null,
                'receipts' => 'I',
                'transaction_date' => now(),
                'transaction_type' => 'Cash',
                'particulars' => 'Opening Balance',
                'debit' => 0,
                'credit' => 0,
                'balance' => 0,
            ],
            [
                'name' => 'STORE CASH',
                'alter_code' => 'STORE-001',
                'under' => 'CASH IN HAND',
                'opening_balance' => 75000.00,
                'opening_balance_type' => 'D',
                'credit_card' => null,
                'bank_charges' => null,
                'address' => 'STORE ROOM',
                'address1' => 'WAREHOUSE',
                'input_gst_purchase' => false,
                'output_gst_income' => false,
                'account_no' => null,
                'report_no' => null,
                'cheque_clearance_method' => 'P',
                'flag' => null,
                'receipts' => 'S',
                'transaction_date' => now(),
                'transaction_type' => 'Cash',
                'particulars' => 'Opening Balance',
                'debit' => 0,
                'credit' => 0,
                'balance' => 0,
            ],
            [
                'name' => 'FEDERAL BANK',
                'alter_code' => 'FEDERAL-001',
                'under' => 'CASH & BANK BALANCES',
                'opening_balance' => 3500000.00,
                'opening_balance_type' => 'D',
                'credit_card' => 'N',
                'bank_charges' => 350.00,
                'address' => 'KOCHI',
                'address1' => 'KOCHI - 682001',
                'input_gst_purchase' => false,
                'output_gst_income' => false,
                'account_no' => '3333444455556666',
                'report_no' => null,
                'cheque_clearance_method' => 'I',
                'flag' => null,
                'receipts' => 'S',
                'transaction_date' => now(),
                'transaction_type' => 'Bank',
                'particulars' => 'Opening Balance',
                'debit' => 0,
                'credit' => 0,
                'balance' => 0,
            ],
            [
                'name' => 'IDBI BANK',
                'alter_code' => 'IDBI-001',
                'under' => 'CASH & BANK BALANCES',
                'opening_balance' => 4200000.00,
                'opening_balance_type' => 'D',
                'credit_card' => 'Y',
                'bank_charges' => 450.00,
                'address' => 'KOLKATA',
                'address1' => 'KOLKATA - 700001',
                'input_gst_purchase' => true,
                'output_gst_income' => false,
                'account_no' => '7777888899990000',
                'report_no' => null,
                'cheque_clearance_method' => 'P',
                'flag' => null,
                'receipts' => 'I',
                'transaction_date' => now(),
                'transaction_type' => 'Bank',
                'particulars' => 'Opening Balance',
                'debit' => 0,
                'credit' => 0,
                'balance' => 0,
            ],
            [
                'name' => 'BOB BANK',
                'alter_code' => 'BOB-001',
                'under' => 'CASH & BANK BALANCES',
                'opening_balance' => 6800000.00,
                'opening_balance_type' => 'D',
                'credit_card' => 'N',
                'bank_charges' => 500.00,
                'address' => 'PUNE',
                'address1' => 'PUNE - 411001',
                'input_gst_purchase' => false,
                'output_gst_income' => true,
                'account_no' => '1010101010101010',
                'report_no' => null,
                'cheque_clearance_method' => 'I',
                'flag' => null,
                'receipts' => 'S',
                'transaction_date' => now(),
                'transaction_type' => 'Bank',
                'particulars' => 'Opening Balance',
                'debit' => 0,
                'credit' => 0,
                'balance' => 0,
            ],
            [
                'name' => 'SBI BANK',
                'alter_code' => 'SBI-001',
                'under' => 'CASH & BANK BALANCES',
                'opening_balance' => 20000000.00,
                'opening_balance_type' => 'D',
                'credit_card' => 'N',
                'bank_charges' => 400.00,
                'address' => 'DELHI',
                'address1' => 'DELHI - 110001',
                'input_gst_purchase' => true,
                'output_gst_income' => true,
                'account_no' => '1212121212121212',
                'report_no' => null,
                'cheque_clearance_method' => 'I',
                'flag' => null,
                'receipts' => 'S',
                'transaction_date' => now(),
                'transaction_type' => 'Bank',
                'particulars' => 'Opening Balance',
                'debit' => 0,
                'credit' => 0,
                'balance' => 0,
            ],
        ];

        foreach ($fakeBooks as $book) {
            CashBankBook::create($book);
        }
    }
}
