<?php

namespace Database\Seeders;

use App\Models\PersonalDirectory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PersonalDirectorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $entries = [
            [
                'name' => 'Rajesh Kumar',
                'alt_code' => 'RK001',
                'address_office' => 'Office: 123 Business Park\nMumbai, Maharashtra 400001',
                'address_residence' => 'Residence: Flat 5, Sunrise Apartments\nMumbai, Maharashtra 400002',
                'tel_office' => '022-1234567',
                'tel_residence' => '022-7654321',
                'mobile' => '9876543210',
                'fax' => '022-1234568',
                'email' => 'rajesh.kumar@company.com',
                'status' => 'Active',
                'contact_person' => 'Rajesh Kumar',
                'birthday' => '1985-05-15',
                'anniversary' => '2010-06-20',
                'spouse' => 'Priya Kumar',
                'spouse_dob' => '1987-08-22',
                'child_1' => 'Arjun Kumar',
                'child_1_dob' => '2012-03-10',
                'child_2' => 'Isha Kumar',
                'child_2_dob' => '2015-07-18',
            ],
            [
                'name' => 'Priya Sharma',
                'alt_code' => 'PS002',
                'address_office' => 'Office: 456 Corporate Tower\nDelhi, Delhi 110001',
                'address_residence' => 'Residence: House 12, Green Valley\nDelhi, Delhi 110002',
                'tel_office' => '011-2345678',
                'tel_residence' => '011-8765432',
                'mobile' => '9876543211',
                'fax' => '011-2345679',
                'email' => 'priya.sharma@company.com',
                'status' => 'Active',
                'contact_person' => 'Priya Sharma',
                'birthday' => '1988-12-08',
                'anniversary' => '2012-01-15',
                'spouse' => 'Amit Sharma',
                'spouse_dob' => '1986-09-12',
                'child_1' => 'Rohan Sharma',
                'child_1_dob' => '2013-05-22',
                'child_2' => null,
                'child_2_dob' => null,
            ],
            [
                'name' => 'Amit Patel',
                'alt_code' => 'AP003',
                'address_office' => 'Office: 789 Trade Center\nAhmedabad, Gujarat 380001',
                'address_residence' => 'Residence: Villa 7, Sapphire Society\nAhmedabad, Gujarat 380002',
                'tel_office' => '079-3456789',
                'tel_residence' => '079-9876543',
                'mobile' => '9876543212',
                'fax' => '079-3456790',
                'email' => 'amit.patel@company.com',
                'status' => 'Active',
                'contact_person' => 'Amit Patel',
                'birthday' => '1982-03-25',
                'anniversary' => '2008-11-30',
                'spouse' => 'Neha Patel',
                'spouse_dob' => '1984-07-14',
                'child_1' => 'Aditya Patel',
                'child_1_dob' => '2010-02-08',
                'child_2' => 'Ananya Patel',
                'child_2_dob' => '2014-09-16',
            ],
            [
                'name' => 'Sneha Reddy',
                'alt_code' => 'SR004',
                'address_office' => 'Office: 321 Tech Park\nHyderabad, Telangana 500001',
                'address_residence' => 'Residence: Apartment 15, Pearl Heights\nHyderabad, Telangana 500002',
                'tel_office' => '040-4567890',
                'tel_residence' => '040-0987654',
                'mobile' => '9876543213',
                'fax' => '040-4567891',
                'email' => 'sneha.reddy@company.com',
                'status' => 'Active',
                'contact_person' => 'Sneha Reddy',
                'birthday' => '1990-11-18',
                'anniversary' => '2015-02-14',
                'spouse' => 'Vikram Reddy',
                'spouse_dob' => '1989-06-20',
                'child_1' => null,
                'child_1_dob' => null,
                'child_2' => null,
                'child_2_dob' => null,
            ],
            [
                'name' => 'Vikram Singh',
                'alt_code' => 'VS005',
                'address_office' => 'Office: 654 Business Hub\nJaipur, Rajasthan 302001',
                'address_residence' => 'Residence: Bungalow 8, Royal Gardens\nJaipur, Rajasthan 302002',
                'tel_office' => '0141-5678901',
                'tel_residence' => '0141-1098765',
                'mobile' => '9876543214',
                'fax' => '0141-5678902',
                'email' => 'vikram.singh@company.com',
                'status' => 'Active',
                'contact_person' => 'Vikram Singh',
                'birthday' => '1987-04-10',
                'anniversary' => '2011-05-22',
                'spouse' => 'Kavya Singh',
                'spouse_dob' => '1989-09-05',
                'child_1' => 'Aryan Singh',
                'child_1_dob' => '2013-12-14',
                'child_2' => null,
                'child_2_dob' => null,
            ],
            [
                'name' => 'Kavya Nair',
                'alt_code' => 'KN006',
                'address_office' => 'Office: 987 Commerce Plaza\nKochi, Kerala 682001',
                'address_residence' => 'Residence: Flat 20, Emerald Towers\nKochi, Kerala 682002',
                'tel_office' => '0484-6789012',
                'tel_residence' => '0484-2109876',
                'mobile' => '9876543215',
                'fax' => '0484-6789013',
                'email' => 'kavya.nair@company.com',
                'status' => 'Inactive',
                'contact_person' => 'Kavya Nair',
                'birthday' => '1991-07-28',
                'anniversary' => '2016-08-10',
                'spouse' => 'Arun Nair',
                'spouse_dob' => '1990-12-15',
                'child_1' => 'Aditya Nair',
                'child_1_dob' => '2017-04-20',
                'child_2' => null,
                'child_2_dob' => null,
            ],
            [
                'name' => 'Arjun Gupta',
                'alt_code' => 'AG007',
                'address_office' => 'Office: 147 Enterprise Square\nKolkata, West Bengal 700001',
                'address_residence' => 'Residence: House 25, Jade Park\nKolkata, West Bengal 700002',
                'tel_office' => '033-7890123',
                'tel_residence' => '033-3210987',
                'mobile' => '9876543216',
                'fax' => '033-7890124',
                'email' => 'arjun.gupta@company.com',
                'status' => 'Active',
                'contact_person' => 'Arjun Gupta',
                'birthday' => '1984-01-12',
                'anniversary' => '2009-03-18',
                'spouse' => 'Divya Gupta',
                'spouse_dob' => '1986-05-22',
                'child_1' => 'Rishi Gupta',
                'child_1_dob' => '2011-08-30',
                'child_2' => 'Rani Gupta',
                'child_2_dob' => '2014-11-25',
            ],
            [
                'name' => 'Meera Iyer',
                'alt_code' => 'MI008',
                'address_office' => 'Office: 258 Business District\nChennai, Tamil Nadu 600001',
                'address_residence' => 'Residence: Apartment 12, Ruby Residency\nChennai, Tamil Nadu 600002',
                'tel_office' => '044-8901234',
                'tel_residence' => '044-4321098',
                'mobile' => '9876543217',
                'fax' => '044-8901235',
                'email' => 'meera.iyer@company.com',
                'status' => 'Active',
                'contact_person' => 'Meera Iyer',
                'birthday' => '1989-06-14',
                'anniversary' => '2013-07-25',
                'spouse' => 'Rajesh Iyer',
                'spouse_dob' => '1988-10-08',
                'child_1' => null,
                'child_1_dob' => null,
                'child_2' => null,
                'child_2_dob' => null,
            ],
            [
                'name' => 'Sanjay Verma',
                'alt_code' => 'SV009',
                'address_office' => 'Office: 369 Corporate Center\nBangalore, Karnataka 560001',
                'address_residence' => 'Residence: Villa 15, Tech Park Villas\nBangalore, Karnataka 560002',
                'tel_office' => '080-9012345',
                'tel_residence' => '080-5432109',
                'mobile' => '9876543218',
                'fax' => '080-9012346',
                'email' => 'sanjay.verma@company.com',
                'status' => 'Active',
                'contact_person' => 'Sanjay Verma',
                'birthday' => '1986-09-20',
                'anniversary' => '2010-10-12',
                'spouse' => 'Anjali Verma',
                'spouse_dob' => '1988-02-28',
                'child_1' => 'Vivaan Verma',
                'child_1_dob' => '2012-06-15',
                'child_2' => 'Zara Verma',
                'child_2_dob' => '2015-01-22',
            ],
            [
                'name' => 'Pooja Desai',
                'alt_code' => 'PD010',
                'address_office' => 'Office: 741 Trade Tower\nPune, Maharashtra 411001',
                'address_residence' => 'Residence: Flat 8, Sapphire Apartments\nPune, Maharashtra 411002',
                'tel_office' => '020-0123456',
                'tel_residence' => '020-6543210',
                'mobile' => '9876543219',
                'fax' => '020-0123457',
                'email' => 'pooja.desai@company.com',
                'status' => 'Active',
                'contact_person' => 'Pooja Desai',
                'birthday' => '1992-02-05',
                'anniversary' => '2017-04-08',
                'spouse' => 'Nikhil Desai',
                'spouse_dob' => '1991-08-18',
                'child_1' => 'Arav Desai',
                'child_1_dob' => '2018-09-12',
                'child_2' => null,
                'child_2_dob' => null,
            ],
            [
                'name' => 'Rohit Mishra',
                'alt_code' => 'RM011',
                'address_office' => 'Office: 852 Enterprise Plaza\nLucknow, Uttar Pradesh 226001',
                'address_residence' => 'Residence: Villa 10, Green Meadows\nLucknow, Uttar Pradesh 226002',
                'tel_office' => '0522-1234567',
                'tel_residence' => '0522-7654321',
                'mobile' => '9876543220',
                'fax' => '0522-1234568',
                'email' => 'rohit.mishra@company.com',
                'status' => 'Active',
                'contact_person' => 'Rohit Mishra',
                'birthday' => '1985-11-30',
                'anniversary' => '2009-12-25',
                'spouse' => 'Sneha Mishra',
                'spouse_dob' => '1987-03-14',
                'child_1' => 'Vivaan Mishra',
                'child_1_dob' => '2011-07-20',
                'child_2' => 'Isha Mishra',
                'child_2_dob' => '2014-04-15',
            ],
            [
                'name' => 'Anita Singh',
                'alt_code' => 'AS012',
                'address_office' => 'Office: 963 Business Complex\nIndore, Madhya Pradesh 452001',
                'address_residence' => 'Residence: Apartment 22, Crystal Heights\nIndore, Madhya Pradesh 452002',
                'tel_office' => '0731-2345678',
                'tel_residence' => '0731-8765432',
                'mobile' => '9876543221',
                'fax' => '0731-2345679',
                'email' => 'anita.singh@company.com',
                'status' => 'Active',
                'contact_person' => 'Anita Singh',
                'birthday' => '1988-08-12',
                'anniversary' => '2011-09-18',
                'spouse' => 'Rajesh Singh',
                'spouse_dob' => '1986-12-05',
                'child_1' => null,
                'child_1_dob' => null,
                'child_2' => null,
                'child_2_dob' => null,
            ],
            [
                'name' => 'Deepak Kumar',
                'alt_code' => 'DK013',
                'address_office' => 'Office: 147 Corporate Hub\nNagpur, Maharashtra 440001',
                'address_residence' => 'Residence: House 18, Jade Villas\nNagpur, Maharashtra 440002',
                'tel_office' => '0712-3456789',
                'tel_residence' => '0712-9876543',
                'mobile' => '9876543222',
                'fax' => '0712-3456790',
                'email' => 'deepak.kumar@company.com',
                'status' => 'Active',
                'contact_person' => 'Deepak Kumar',
                'birthday' => '1983-05-22',
                'anniversary' => '2007-06-10',
                'spouse' => 'Ritu Kumar',
                'spouse_dob' => '1985-10-08',
                'child_1' => 'Arjun Kumar',
                'child_1_dob' => '2009-01-25',
                'child_2' => 'Ananya Kumar',
                'child_2_dob' => '2012-08-30',
            ],
            [
                'name' => 'Neha Patel',
                'alt_code' => 'NP014',
                'address_office' => 'Office: 258 Trade Center\nSurat, Gujarat 395001',
                'address_residence' => 'Residence: Flat 15, Diamond Plaza\nSurat, Gujarat 395002',
                'tel_office' => '0261-4567890',
                'tel_residence' => '0261-0987654',
                'mobile' => '9876543223',
                'fax' => '0261-4567891',
                'email' => 'neha.patel@company.com',
                'status' => 'Active',
                'contact_person' => 'Neha Patel',
                'birthday' => '1990-09-16',
                'anniversary' => '2014-10-22',
                'spouse' => 'Harsh Patel',
                'spouse_dob' => '1989-04-10',
                'child_1' => 'Aditya Patel',
                'child_1_dob' => '2015-11-08',
                'child_2' => null,
                'child_2_dob' => null,
            ],
            [
                'name' => 'Suresh Reddy',
                'alt_code' => 'SR015',
                'address_office' => 'Office: 369 Business District\nVijayawada, Andhra Pradesh 520001',
                'address_residence' => 'Residence: Villa 12, Emerald Gardens\nVijayawada, Andhra Pradesh 520002',
                'tel_office' => '0866-5678901',
                'tel_residence' => '0866-1098765',
                'mobile' => '9876543224',
                'fax' => '0866-5678902',
                'email' => 'suresh.reddy@company.com',
                'status' => 'Inactive',
                'contact_person' => 'Suresh Reddy',
                'birthday' => '1981-07-03',
                'anniversary' => '2005-08-12',
                'spouse' => 'Lakshmi Reddy',
                'spouse_dob' => '1983-11-28',
                'child_1' => 'Rahul Reddy',
                'child_1_dob' => '2008-03-15',
                'child_2' => 'Priya Reddy',
                'child_2_dob' => '2011-06-20',
            ],
            [
                'name' => 'Mohit Verma',
                'alt_code' => 'MV016',
                'address_office' => 'Office: 741 Enterprise Center\nLudhiana, Punjab 141001',
                'address_residence' => 'Residence: Apartment 20, Ruby Towers\nLudhiana, Punjab 141002',
                'tel_office' => '0161-6789012',
                'tel_residence' => '0161-2109876',
                'mobile' => '9876543225',
                'fax' => '0161-6789013',
                'email' => 'mohit.verma@company.com',
                'status' => 'Active',
                'contact_person' => 'Mohit Verma',
                'birthday' => '1986-04-19',
                'anniversary' => '2010-05-28',
                'spouse' => 'Anjali Verma',
                'spouse_dob' => '1988-01-12',
                'child_1' => 'Vihaan Verma',
                'child_1_dob' => '2012-10-05',
                'child_2' => null,
                'child_2_dob' => null,
            ],
            [
                'name' => 'Priya Gupta',
                'alt_code' => 'PG017',
                'address_office' => 'Office: 852 Corporate Tower\nChandigarh, Chandigarh 160001',
                'address_residence' => 'Residence: House 25, Sapphire Park\nChandigarh, Chandigarh 160002',
                'tel_office' => '0172-7890123',
                'tel_residence' => '0172-3210987',
                'mobile' => '9876543226',
                'fax' => '0172-7890124',
                'email' => 'priya.gupta@company.com',
                'status' => 'Active',
                'contact_person' => 'Priya Gupta',
                'birthday' => '1991-01-07',
                'anniversary' => '2016-02-14',
                'spouse' => 'Arjun Gupta',
                'spouse_dob' => '1990-08-22',
                'child_1' => 'Arav Gupta',
                'child_1_dob' => '2017-05-10',
                'child_2' => null,
                'child_2_dob' => null,
            ],
            [
                'name' => 'Vikram Rao',
                'alt_code' => 'VR018',
                'address_office' => 'Office: 963 Business Plaza\nVishakapatnam, Andhra Pradesh 530001',
                'address_residence' => 'Residence: Flat 18, Coral Residency\nVishakapatnam, Andhra Pradesh 530002',
                'tel_office' => '0891-8901234',
                'tel_residence' => '0891-4321098',
                'mobile' => '9876543227',
                'fax' => '0891-8901235',
                'email' => 'vikram.rao@company.com',
                'status' => 'Active',
                'contact_person' => 'Vikram Rao',
                'birthday' => '1984-10-14',
                'anniversary' => '2008-11-20',
                'spouse' => 'Divya Rao',
                'spouse_dob' => '1986-06-10',
                'child_1' => 'Rohan Rao',
                'child_1_dob' => '2010-09-18',
                'child_2' => 'Isha Rao',
                'child_2_dob' => '2013-12-22',
            ],
            [
                'name' => 'Swati Sharma',
                'alt_code' => 'SS019',
                'address_office' => 'Office: 147 Trade Hub\nBhopal, Madhya Pradesh 462001',
                'address_residence' => 'Residence: Villa 14, Green Valley\nBhopal, Madhya Pradesh 462002',
                'tel_office' => '0755-9012345',
                'tel_residence' => '0755-5432109',
                'mobile' => '9876543228',
                'fax' => '0755-9012346',
                'email' => 'swati.sharma@company.com',
                'status' => 'Active',
                'contact_person' => 'Swati Sharma',
                'birthday' => '1989-03-28',
                'anniversary' => '2012-04-15',
                'spouse' => 'Nitin Sharma',
                'spouse_dob' => '1988-09-05',
                'child_1' => null,
                'child_1_dob' => null,
                'child_2' => null,
                'child_2_dob' => null,
            ],
            [
                'name' => 'Ashok Nair',
                'alt_code' => 'AN020',
                'address_office' => 'Office: 258 Enterprise Square\nThiruvananthapuram, Kerala 695001',
                'address_residence' => 'Residence: Apartment 25, Opal Towers\nThiruvananthapuram, Kerala 695002',
                'tel_office' => '0471-0123456',
                'tel_residence' => '0471-6543210',
                'mobile' => '9876543229',
                'fax' => '0471-0123457',
                'email' => 'ashok.nair@company.com',
                'status' => 'Active',
                'contact_person' => 'Ashok Nair',
                'birthday' => '1982-12-11',
                'anniversary' => '2006-01-20',
                'spouse' => 'Meera Nair',
                'spouse_dob' => '1984-07-15',
                'child_1' => 'Arjun Nair',
                'child_1_dob' => '2009-05-08',
                'child_2' => 'Ananya Nair',
                'child_2_dob' => '2012-10-12',
            ],
        ];

        foreach ($entries as $entry) {
            PersonalDirectory::create($entry);
        }
    }
}
