<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up()
    {
        Schema::create('item_master', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->double('code')->nullable();
            $table->string('Barcode', 10)->nullable();
            $table->string('name', 10)->nullable();
            $table->double('Compcode')->nullable();
            $table->string('Compname', 10)->nullable();
            $table->string('Pack', 10)->nullable();
            $table->double('Unit')->nullable();
            $table->string('Location', 10)->nullable();
            $table->string('Expiry', 10)->nullable();
            $table->string('Generic', 10)->nullable();
            $table->double('Saltcode')->nullable();
            $table->string('Strength', 10)->nullable();
            $table->double('saltcode1')->nullable();
            $table->string('Strength1', 10)->nullable();
            $table->double('saltcode2')->nullable();
            $table->string('Strength2', 10)->nullable();
            $table->double('saltcode3')->nullable();
            $table->string('Strength3', 10)->nullable();
            $table->double('Saltcode4')->nullable();
            $table->string('Strength4', 10)->nullable();
            $table->double('Saltcode5')->nullable();
            $table->string('Strength5', 10)->nullable();
            $table->string('Substitute', 10)->nullable();
            $table->double('Saltno')->nullable();
            $table->double('Prate')->nullable();
            $table->double('Tsr')->nullable();
            $table->double('Psc')->nullable();
            $table->double('ptax')->nullable();
            $table->double('Excise')->nullable();
            $table->double('Scm1')->nullable();
            $table->double('scm2')->nullable();
            $table->double('Srate')->nullable();
            $table->double('Sc')->nullable();
            $table->double('Saletype')->nullable();
            $table->double('Stax')->nullable();
            $table->double('Wsrate')->nullable();
            $table->string('Add_sc', 10)->nullable();
            $table->string('Add_tsr', 10)->nullable();
            $table->double('Costrate')->nullable();
            $table->double('opqty')->nullable();
            $table->double('Clqty')->nullable();
            $table->string('status', 10)->nullable();
            $table->string('Vdt', 10)->nullable();
            $table->string('Batchcode', 10)->nullable();
            $table->string('cname_bc', 10)->nullable();
            $table->string('Defqty', 10)->nullable();
            $table->double('BarcodeQty')->nullable();
            $table->double('splrate')->nullable();
            $table->double('Mrp')->nullable();
            $table->double('Ssc')->nullable();
            $table->string('WsNet', 10)->nullable();
            $table->string('SplNet', 10)->nullable();
            $table->string('Hscm', 10)->nullable();
            $table->double('Box')->nullable();
            $table->string('CommonItem', 10)->nullable();
            $table->double('Sscm1')->nullable();
            $table->string('FDis', 10)->nullable();
            $table->double('Sscm2')->nullable();
            $table->double('FDisP')->nullable();
            $table->string('currentScm', 10)->nullable();
            $table->string('ScmFrom', 10)->nullable();
            $table->string('ScmTo', 10)->nullable();
            $table->double('CurrScm1')->nullable();
            $table->double('CurrScm2')->nullable();
            $table->string('TrimName', 10)->nullable();
            $table->string('PresReq', 10)->nullable();
            $table->string('Division', 10)->nullable();
            $table->string('QScm', 10)->nullable();
            $table->double('SconMrp')->nullable();
            $table->double('VAT')->nullable();
            $table->double('Margin')->nullable();
            $table->string('Inclusive', 10)->nullable();
            $table->double('ItemCat')->nullable();
            $table->double('Gdn')->nullable();
            $table->double('PRateCase')->nullable();
            $table->double('PRateBox')->nullable();
            $table->string('Desc1', 10)->nullable();
            $table->string('Desc2', 10)->nullable();
            $table->double('MinQty')->nullable();
            $table->double('MaxQty')->nullable();
            $table->double('ItCase')->nullable();
            $table->double('TRate')->nullable();
            $table->string('Wr', 10)->nullable();
            $table->string('Pic', 10)->nullable();
            $table->string('Mfg', 10)->nullable();
            $table->double('TempOpqty')->nullable();
            $table->double('TempClqty')->nullable();
            $table->double('TempAmt')->nullable();
            $table->double('TempAmt1')->nullable();
            $table->double('TempAmt2')->nullable();
            $table->string('TaxonMrp', 10)->nullable();
            $table->double('ScmPer')->nullable();
            $table->double('IWeight')->nullable();
            $table->string('SubStrenght', 10)->nullable();
            $table->string('ItemRef', 10)->nullable();
            $table->double('MaxInvQty')->nullable();
            $table->string('MaxQtyWr', 10)->nullable();
            $table->string('OpFreeQty', 10)->nullable();
            $table->string('VATonSrate', 10)->nullable();
            $table->string('Exon', 10)->nullable();
            $table->double('ExPer')->nullable();
            $table->double('UnitType')->nullable();
            $table->double('MfgQty')->nullable();
            $table->string('mTag', 10)->nullable();
            $table->string('DisContinue', 10)->nullable();
            $table->string('MfgBy', 10)->nullable();
            $table->double('Vol')->nullable();
            $table->double('VDisP')->nullable();
            $table->double('VDisS')->nullable();
            $table->string('FDisWR', 10)->nullable();
            $table->double('LastYearCost')->nullable();
            $table->double('OpAddQty')->nullable();
            $table->double('SaleLessQty')->nullable();
            $table->double('SplDisQty')->nullable();
            $table->double('SplDisPer')->nullable();
            $table->double('MinGP')->nullable();
            $table->string('LockScm', 10)->nullable();
            $table->string('FullName', 10)->nullable();
            $table->string('RateLock', 10)->nullable();
            $table->double('MinRate')->nullable();
            $table->double('PurExciseAsRate')->nullable();
            $table->double('PurNetRate')->nullable();
            $table->double('CostWFQ')->nullable();
            $table->string('LockBilling', 10)->nullable();
            $table->double('SameBatchCost')->nullable();
            $table->double('EsCode')->nullable();
            $table->string('FdisPWS', 10)->nullable();
            $table->string('ItemType', 10)->nullable();
            $table->double('ItemGroup')->nullable();
            $table->string('HSNCode', 10)->nullable();
            $table->double('CGST')->nullable();
            $table->double('SGST')->nullable();
            $table->double('IGST')->nullable();
            $table->double('GSTCess')->nullable();
            $table->string('IucCode', 10)->nullable();
            $table->string('Flag', 10)->nullable();
            $table->string('miscsettings', 10)->nullable();
            $table->string('SyncMark', 10)->nullable();
            $table->boolean('is_deleted')->default(false);
            $table->timestamps();
            
            $table->index('code');
            $table->index('name');
            $table->index('Compcode');
            $table->index('is_deleted');
        });
    }

    public function down()
    {
        Schema::dropIfExists('item_master');
    }
};